// <auto-generated />
namespace GoAgile.DataContexts.AgileDbMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddColorRetrospectiveItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddColorRetrospectiveItems));
        
        string IMigrationMetadata.Id
        {
            get { return "201612142050071_AddColorRetrospectiveItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
