// <auto-generated />
namespace GoAgile.DataContexts.AgileDbMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedVotes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedVotes));
        
        string IMigrationMetadata.Id
        {
            get { return "201611222321078_AddedVotes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
